/*
 * Ansible Tower API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data17 struct {
	// 
	CapacityAdjustment float32 `json:"capacity_adjustment,omitempty"`
	// 
	Enabled bool `json:"enabled,omitempty"`
	// 
	ManagedByPolicy bool `json:"managed_by_policy,omitempty"`
}
