/*
 * Ansible Tower API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body10 struct {
	Description string `json:"description,omitempty"`
	// Is this host online and available for running jobs?
	Enabled string `json:"enabled,omitempty"`
	// The value used by the remote inventory source to uniquely identify the host
	InstanceId string `json:"instance_id,omitempty"`
	Inventory  int32  `json:"inventory"`
	Name       string `json:"name"`
	// Host variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
}
