/*
 * Ansible Tower API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body46 struct {
	AllowSimultaneous     string `json:"allow_simultaneous,omitempty"`
	AskCredentialOnLaunch string `json:"ask_credential_on_launch,omitempty"`
	AskDiffModeOnLaunch   string `json:"ask_diff_mode_on_launch,omitempty"`
	AskInventoryOnLaunch  string `json:"ask_inventory_on_launch,omitempty"`
	AskJobTypeOnLaunch    string `json:"ask_job_type_on_launch,omitempty"`
	AskLimitOnLaunch      string `json:"ask_limit_on_launch,omitempty"`
	AskScmBranchOnLaunch  string `json:"ask_scm_branch_on_launch,omitempty"`
	AskSkipTagsOnLaunch   string `json:"ask_skip_tags_on_launch,omitempty"`
	AskTagsOnLaunch       string `json:"ask_tags_on_launch,omitempty"`
	AskVariablesOnLaunch  string `json:"ask_variables_on_launch,omitempty"`
	AskVerbosityOnLaunch  string `json:"ask_verbosity_on_launch,omitempty"`
	BecomeEnabled         string `json:"become_enabled,omitempty"`
	// Local absolute file path containing a custom Python virtualenv to use
	CustomVirtualenv string `json:"custom_virtualenv,omitempty"`
	Description      string `json:"description,omitempty"`
	// If enabled, textual changes made to any templated files on the host are shown in the standard output
	DiffMode      string `json:"diff_mode,omitempty"`
	ExtraVars     string `json:"extra_vars,omitempty"`
	ForceHandlers string `json:"force_handlers,omitempty"`
	Forks         int32  `json:"forks,omitempty"`
	HostConfigKey string `json:"host_config_key,omitempty"`
	Inventory     int32  `json:"inventory,omitempty"`
	// The number of jobs to slice into at runtime. Will cause the Job Template to launch a workflow if value is greater than 1.
	JobSliceCount int32  `json:"job_slice_count,omitempty"`
	JobTags       string `json:"job_tags,omitempty"`
	JobType       string `json:"job_type,omitempty"`
	Limit         string `json:"limit,omitempty"`
	Name          string `json:"name"`
	Playbook      string `json:"playbook,omitempty"`
	Project       string `json:"project,omitempty"`
	// Branch to use in job run. Project default used if blank. Only allowed if project allow_override field is set to true.
	ScmBranch     string `json:"scm_branch,omitempty"`
	SkipTags      string `json:"skip_tags,omitempty"`
	StartAtTask   string `json:"start_at_task,omitempty"`
	SurveyEnabled string `json:"survey_enabled,omitempty"`
	// The amount of time (in seconds) to run before the task is canceled.
	Timeout int32 `json:"timeout,omitempty"`
	// If enabled, Tower will act as an Ansible Fact Cache Plugin; persisting facts at the end of a playbook run to the database and caching facts for use by Ansible.
	UseFactCache string `json:"use_fact_cache,omitempty"`
	Verbosity    string `json:"verbosity,omitempty"`
	// Personal Access Token for posting back the status to the service API
	WebhookCredential int32 `json:"webhook_credential,omitempty"`
	// Service that webhook requests will be accepted from
	WebhookService string `json:"webhook_service,omitempty"`
}
