/*
 * Ansible Tower API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body18 struct {
	CapacityAdjustment float64 `json:"capacity_adjustment,omitempty"`
	Enabled            string  `json:"enabled,omitempty"`
	ManagedByPolicy    string  `json:"managed_by_policy,omitempty"`
}
